parameters:
    app.api.doc_config_file: '%kernel.config_dir%/api_doc.yaml'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Api\:
        resource: '../../src/Api/*'

    App\Api\Controller\:
        resource: '../../src/Api/Controller'
        tags: [controller.service_arguments]

    App\Api\Serializer\Response\ExceptionNormalizer:
        $debug: '%kernel.debug%'
