parameters:
    app.api.doc_config_file: '%kernel.config_dir%/api_doc.yaml'
    app.api.path_prefix: '/api/'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Api\:
        resource: '../../src/Api/*'

    App\Api\Controller\:
        resource: '../../src/Api/Controller'
        tags: [controller.service_arguments]

    App\Api\Http\Controller\EntityValueResolver:
        tags: [{name: controller.argument_value_resolver, priority: -96}]

    App\Api\Http\Controller\InputObjectValueResolver:
        tags: [{name: controller.argument_value_resolver, priority: -128}]

    App\Api\Http\Listener\MarkApiEndpointsListener:
        arguments: ['%app.api.path_prefix%']

    app.api.http.listener.symfony_exception_listener:
        class: Symfony\Component\HttpKernel\EventListener\ErrorListener
        arguments: {$controller: 'App\Api\Controller\ErrorController::error', $debug: '%kernel.debug%'}

    App\Api\Http\Listener\ExceptionListener:
        arguments: ['@app.api.http.listener.symfony_exception_listener']

    App\Api\Serializer\ExceptionNormalizer:
        arguments: ['%kernel.debug%']
        tags: [{name: serializer.normalizer, priority: -100}]
