parameters:
    env(PUBLIC_FILESYSTEM): local
    env(PRIVATE_FILESYSTEM): local

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Common\:
        resource: '../../src/Common/*'

    App\Common\Filesystem\Adapter\PublicLocalFilesystemAdapter:
        arguments: ['%kernel.project_dir%/public']

    app.common.filesystem.public_adapter_locator:
        class: Symfony\Component\DependencyInjection\ServiceLocator
        arguments: [{local: '@App\Common\Filesystem\Adapter\PublicLocalFilesystemAdapter'}]

    League\Flysystem\Local\LocalFilesystemAdapter:
        arguments: ['%kernel.project_dir%/upload']

    app.common.filesystem.private_adapter_locator:
        class: Symfony\Component\DependencyInjection\ServiceLocator
        arguments: [{local: '@League\Flysystem\Local\LocalFilesystemAdapter'}]

    App\Common\Filesystem\PublicFilesystemAdapter:
        factory: ['@app.common.filesystem.public_adapter_locator', get]
        arguments: ['%env(PUBLIC_FILESYSTEM)%']

    League\Flysystem\FilesystemAdapter:
        factory: ['@app.common.filesystem.private_adapter_locator', get]
        arguments: ['%env(PRIVATE_FILESYSTEM)%']

    App\Common\Filesystem\PublicFilesystem:
        arguments: ['@App\Common\Filesystem\PublicFilesystemAdapter']

    League\Flysystem\Filesystem:
        arguments: ['@League\Flysystem\FilesystemAdapter']
