parameters:
    env(PUBLIC_FILESYSTEM): public_local
    env(PRIVATE_FILESYSTEM): private_local

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Common\:
        resource: '../../src/Common/*'

    app.common.filesystem.adapter.public_local:
        class: League\Flysystem\Local\LocalFilesystemAdapter
        arguments: ['%kernel.project_dir%/public']

    app.common.filesystem.adapter.private_local:
        class: League\Flysystem\Local\LocalFilesystemAdapter
        arguments: ['%kernel.project_dir%/upload']

    app.common.filesystem.adapter_locator:
        class: Symfony\Component\DependencyInjection\ServiceLocator
        arguments:
            -
                public_local: '@app.common.filesystem.adapter.public_local'
                private_local: '@app.common.filesystem.adapter.private_local'

    app.common.filesystem.public_adapter:
        class: League\Flysystem\FilesystemAdapter
        factory: ['@app.common.filesystem.adapter_locator', get]
        arguments: ['%env(PUBLIC_FILESYSTEM)%']

    app.common.filesystem.private_adapter:
        class: League\Flysystem\FilesystemAdapter
        factory: ['@app.common.filesystem.adapter_locator', get]
        arguments: ['%env(PRIVATE_FILESYSTEM)%']

    app.common.filesystem.public:
        class: League\Flysystem\Filesystem
        arguments: ['@app.common.filesystem.public_adapter']

    app.common.filesystem.private:
        class: League\Flysystem\Filesystem
        arguments: ['@app.common.filesystem.private_adapter']
