doctrine:
    driver: pdo_mysql
    url: '%env(resolve:DATABASE_URL)%'
    server_version: '8.0'
    charset: utf8mb4
    default_table_options:
        charset: utf8mb4
        collate: utf8mb4_unicode_ci
