services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Frontend\:
        resource: '../../src/Frontend/*'

    App\Frontend\Controller\:
        resource: '../../src/Frontend/Controller'
        tags: [controller.service_arguments]
