services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Image\:
        resource: '../../src/Image/*'
        exclude: '../../src/Image/{Model}'

    App\Image\Controller\:
        resource: '../../src/Image/Controller'
        tags: [controller.service_arguments]

    Imagine\Gd\Imagine: ~
    Imagine\Image\ImagineInterface: '@Imagine\Gd\Imagine'

    App\Image\Style\ImageStyler:
        $imageStylesLocator: !tagged_locator {tag: app.image.style, index_by: name, default_index_method: getName}
