security:
    encoders:
        App\User\Model\User: auto

    firewalls:
        frontend:
            path: ^/(?!api/)
            security: false

        api_documentation:
            path: ^/api/doc/$
            security: false

        api:
            path: ^/api/
            authenticators: [App\User\Security\Authenticator]
            user_provider: App\User\Security\UserProvider
