security:
    encoders:
        App\User\Model\User: auto

    firewalls:
        frontend:
            path: ^/(?!api/)
            security: false

        api_doc:
            path: ^/api/doc/
            security: false

        api:
            path: ^/api/
            entry_point: App\User\Security\AuthenticationEntryPoint
            access_denied_handler: App\User\Security\AccessDeniedHandler
            logout: {path: /api/user/logout}
            authenticators: [App\User\Security\Authenticator]
            user_provider: App\User\Security\UserProvider

    access_control:
        - {path: ^/api/user/login$, roles: IS_ANONYMOUS}
        - {path: ^/api/user$, methods: POST, roles: IS_ANONYMOUS}
        - {path: ^/api, roles: IS_AUTHENTICATED_FULLY}
