security:
    encoders:
        App\User\Model\User: auto

    firewalls:
        frontend:
            path: ^/(?!api/)
            security: false

        api_doc:
            path: ^/api/doc/
            security: false

        api:
            path: ^/api/
            entry_point: App\User\Security\AuthenticationEntryPoint
            authenticators: [App\User\Security\Authenticator]
            user_provider: App\User\Security\UserProvider
