security:
    encoders:
        App\User\Model\User: auto

    firewalls:
        frontend:
            path: ^/(?!api/)
            security: false

        api_doc:
            path: ^/api/doc
            security: false

        api_login:
            path: ^/api/user/login$
            methods: POST
            stateless: true
            entry_point: App\User\Security\AuthenticationEntryPoint
            access_denied_handler: App\User\Security\AccessDeniedHandler
            authenticators: [App\User\Security\Authenticator\LoginAuthenticator]
            user_provider: App\User\Security\UserProvider\LoginUserProvider

        api:
            path: ^/api/
            stateless: true
            entry_point: App\User\Security\AuthenticationEntryPoint
            access_denied_handler: App\User\Security\AccessDeniedHandler
            logout: {path: /api/user/logout}
            authenticators: [App\User\Security\Authenticator\TokenAuthenticator]
            user_provider: App\User\Security\UserProvider\TokenUserProvider

    access_control:
        - {path: ^/api/image$, methods: POST, roles: PUBLIC_ACCESS}
        - {path: ^/api/user$, methods: POST, roles: IS_ANONYMOUS}
        - {path: ^/api, roles: IS_AUTHENTICATED_FULLY}
