services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\User\:
        resource: '../../src/User/*'
        exclude: '../../src/User/{Error,Model}'

    App\User\Controller\:
        resource: '../../src/User/Controller'
        tags: [controller.service_arguments]

    App\User\Security\Authenticator:
        $loginPath: /api/user/login
        $userProvider: '@App\User\Security\UserProvider'

    App\User\Security\LogoutListener:
        tags: [{name: kernel.event_subscriber, dispatcher: security.event_dispatcher.api}]

    App\User\User\UserManager:
        $userAuthenticator: '@security.authenticator_manager.api'
