parameters:
    app.user.token_availability: 1440 # One day.

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\User\:
        resource: '../../src/User/*'
        exclude: '../../src/User/{Error,Model}'

    App\User\Controller\:
        resource: '../../src/User/Controller'
        tags: [controller.service_arguments]

    App\User\Security\LogoutListener:
        tags: [{name: kernel.event_subscriber, dispatcher: security.event_dispatcher.api}]

    App\User\Token\TokenManager:
        $tokenAvailability: '%app.user.token_availability%'

    App\User\User\UserManager:
        $userAuthenticator: '@security.authenticator_manager.api_login'
