services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\User\:
        resource: '../../src/User/*'

    App\User\Controller\:
        resource: '../../src/User/Controller'
        tags: [controller.service_arguments]

    App\User\Security\Authenticator:
        $loginPath: /api/login
        $userProvider: '@App\User\Security\UserProvider'

    App\User\User\UserManager:
        $userAuthenticator: '@security.authenticator_manager.api'
