version: "3.7"

services:
    postgres:
        image: postgres:latest
        restart: on-failure
        volumes: ["postgres:/var/lib/postgresql/data"]
        ports: ["5432:5432"]
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    redis:
        image: redis:latest
        restart: on-failure
        volumes: ["redis:/data"]
        ports: ["6379:6379"]

    php:
        build:
            context: ./docker/php
        restart: on-failure
        volumes: ["./:/var/www/sandbox"]
        env_file: [.env]

    node:
        image: node:latest
        user: node
        working_dir: /var/www/sandbox
        command: tail -F anything
        restart: on-failure
        volumes: ["./:/var/www/sandbox"]
        ports: ["8080:8080"]
        env_file: [.env]

    nginx:
        build:
            context: ./docker/nginx
        restart: on-failure
        volumes: ["./public:/var/www/sandbox/public"]
        ports: ["80:80", "443:443"]
        depends_on: [php]

volumes:
    postgres:
        driver: local

    redis:
        driver: local
