app_api_documentation_index:
    path: /api/doc
    methods: GET
    controller: 'App\Api\Controller\DocumentationController::index'
    defaults: {_api_endpoint: false}

app_api_documentation_configuration:
    path: /api/doc/config
    methods: GET
    controller: 'App\Api\Controller\DocumentationController::configuration'
    defaults: {_api_endpoint: false}
