app_image_image_get:
    path: /api/image/{token}/{style}
    methods: GET
    controller: 'App\Image\Controller\ImageController::getImage'

app_image_image_upload:
    path: /api/image
    methods: POST
    controller: 'App\Image\Controller\ImageController::upload'
