app_user_user_login:
    path: /api/user/login
    methods: POST
    controller: 'App\User\Controller\UserController::login'

app_user_user_register:
    path: /api/user
    methods: POST
    controller: 'App\User\Controller\UserController::register'
