App\User\Model\User:
    attributes:
        id:
            groups: [api_response]

        firstName:
            groups: [api_request, api_response]

        lastName:
            groups: [api_request, api_response]

        email:
            groups: [api_request, api_response]

        plainPassword:
            groups: [api_request]
