services:
    Symfony\Component\Cache\Marshaller\DefaultMarshaller: ~

    # Adapters.
    cache.adapter.apcu:
        class: Symfony\Component\Cache\Adapter\ApcuAdapter
        abstract: true
        arguments: [!abstract namespace, 0, !abstract version]
        calls: [[setLogger, ['@Psr\Log\LoggerInterface']]]
        tags: [{name: cache.pool, clearer: cache.clearer.default, reset: reset}]

    cache.adapter.array:
        class: Symfony\Component\Cache\Adapter\ArrayAdapter
        abstract: true
        calls: [[setLogger, ['@Psr\Log\LoggerInterface']]]
        tags: [{name: cache.pool, clearer: cache.clearer.default, reset: reset}]

    cache.adapter.filesystem:
        class: Symfony\Component\Cache\Adapter\FilesystemAdapter
        abstract: true
        arguments:
            - !abstract namespace
            - 0
            - !abstract directory
            - '@Symfony\Component\Cache\Marshaller\DefaultMarshaller'
        calls: [[setLogger, ['@Psr\Log\LoggerInterface']]]
        tags: [{name: cache.pool, clearer: cache.clearer.default, reset: reset}]

    cache.adapter.redis:
        class: Symfony\Component\Cache\Adapter\RedisAdapter
        abstract: true
        arguments: [!abstract provider, !abstract namespace, 0, '@Symfony\Component\Cache\Marshaller\DefaultMarshaller']
        calls: [[setLogger, ['@Psr\Log\LoggerInterface']]]
        tags: [{name: cache.pool, provider: cache.default_provider.redis, clearer: cache.clearer.default, reset: reset}]

    cache.adapter.system:
        class: Symfony\Component\Cache\Adapter\AdapterInterface
        abstract: true
        factory: [Symfony\Component\Cache\Adapter\AbstractAdapter, createSystemCache]
        arguments: [!abstract namespace, 0, !abstract version, !abstract directory, '@Psr\Log\LoggerInterface']
        tags: [{name: cache.pool, clearer: cache.clearer.system, reset: reset}]
    # End of - Adapters.

    cache.app: ~
    Psr\Cache\CacheItemPoolInterface: '@cache.app'
    Symfony\Contracts\Cache\CacheInterface: '@cache.app'

    cache.app.taggable:
        class: Symfony\Component\Cache\Adapter\TagAwareAdapter
        arguments: ['@cache.app']
        public: true

    Symfony\Contracts\Cache\TagAwareCacheInterface: '@cache.app.taggable'

    # System pools.
    cache.system:
        parent: cache.adapter.system
        public: true
        tags: [cache.pool]

    cache.property_access:
        class: Symfony\Component\Cache\Adapter\AdapterInterface
        factory: [Symfony\Component\PropertyAccess\PropertyAccessor, createCache]
        arguments: [!abstract namespace, 0, !abstract version, '@Psr\Log\LoggerInterface']
        tags: [{name: cache.pool, clearer: cache.clearer.system}]

    cache.property_info:
        parent: cache.adapter.system
        tags: [cache.pool]

    cache.serializer:
        parent: cache.adapter.system
        tags: [cache.pool]

    cache.validator:
        parent: cache.adapter.system
        tags: [cache.pool]
    # End of - System pools.

    # Clearers.
    cache.clearer.default:
        class: Symfony\Component\HttpKernel\CacheClearer\Psr6CacheClearer
        arguments: [!abstract pools]

    cache.clearer.global:
        parent: cache.clearer.default

    cache.clearer.system:
        parent: cache.clearer.default
    # End of - Clearers.

    # Commands.
    App\Core\Command\Cache\CacheClearCommand:
        arguments:
            - '%kernel.cache_dir%'
            - '@Symfony\Component\Filesystem\Filesystem'
            - '@Symfony\Component\HttpKernel\CacheClearer\ChainCacheClearer'
        tags: [console.command]

    App\Core\Command\Cache\CachePoolClearCommand:
        arguments: ['@cache.clearer.global']
        tags: [console.command]

    App\Core\Command\Cache\CachePoolDeleteCommand:
        arguments: ['@cache.clearer.global']
        tags: [console.command]

    App\Core\Command\Cache\CachePoolPruneCommand:
        arguments: [!abstract pools]
        tags: [console.command]
    # End of - Commands.
