services:
    kernel:
        class: App\Core\Kernel
        public: true
        synthetic: true

    services_resetter:
        class: Symfony\Component\HttpKernel\DependencyInjection\ServicesResetter
        arguments:
            - ~ # Resettable services.
            - ~ # Reset methods.
        public: true

    Symfony\Component\DependencyInjection\ParameterBag\ContainerBag:
        arguments: ['@service_container']

    Symfony\Component\DependencyInjection\ParameterBag\ContainerBagInterface: '@Symfony\Component\DependencyInjection\ParameterBag\ContainerBag'
    Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface: '@Symfony\Component\DependencyInjection\ParameterBag\ContainerBag'

    Symfony\Component\EventDispatcher\EventDispatcher: ~
    Symfony\Component\EventDispatcher\EventDispatcherInterface: '@Symfony\Component\EventDispatcher\EventDispatcher'
    Symfony\Contracts\EventDispatcher\EventDispatcherInterface: '@Symfony\Component\EventDispatcher\EventDispatcher'

    Psr\EventDispatcher\EventDispatcherInterface:
        alias: Symfony\Component\EventDispatcher\EventDispatcher
        public: true

    Symfony\Component\HttpKernel\CacheClearer\ChainCacheClearer:
        arguments: [!tagged_iterator kernel.cache_clearer]

    Symfony\Component\HttpKernel\CacheClearer\CacheClearerInterface: '@Symfony\Component\HttpKernel\CacheClearer\ChainCacheClearer'

    App\Core\Command\CacheClearCommand:
        arguments:
            - '%kernel.cache_dir%'
            - '@Symfony\Component\Filesystem\Filesystem'
            - '@Symfony\Component\HttpKernel\CacheClearer\ChainCacheClearer'
        tags: [console.command]

    Symfony\Component\HttpKernel\Log\Logger: ~
    Psr\Log\LoggerInterface: '@Symfony\Component\HttpKernel\Log\Logger'

    Symfony\Component\Filesystem\Filesystem: ~
