parameters:
    doctrine.orm.proxy_dir: '%kernel.cache_dir%/doctrine/Proxies'

services:
    App\Core\Doctrine\EventManager: ~

    App\Core\Doctrine\RepositoryFactory: ~

    Doctrine\ORM\EntityManager:
        factory: [Doctrine\ORM\EntityManager, create]
        arguments: [!abstract connection, !abstract config, '@App\Core\Doctrine\EventManager']

    Doctrine\Persistence\ObjectManager:
        alias: Doctrine\ORM\EntityManager
        public: true

    Doctrine\ORM\EntityManagerInterface:
        alias: Doctrine\ORM\EntityManager
        public: true

    Doctrine\DBAL\Connection:
        factory: ['@Doctrine\ORM\EntityManager', getConnection]

    # Commands.
    App\Core\Command\Doctrine\ClearMetadataCacheCommand: {tags: [console.command]}
    App\Core\Command\Doctrine\ClearQueryCacheCommand: {tags: [console.command]}
    App\Core\Command\Doctrine\ClearResultCacheCommand: {tags: [console.command]}

    App\Core\Command\Doctrine\CreateDatabaseCommand:
        arguments: ['@Doctrine\DBAL\Connection']
        tags: [console.command]

    App\Core\Command\Doctrine\CreateSchemaCommand: {tags: [console.command]}

    App\Core\Command\Doctrine\DropDatabaseCommand:
        arguments: ['@Doctrine\DBAL\Connection']
        tags: [console.command]

    App\Core\Command\Doctrine\DropSchemaCommand: {tags: [console.command]}
    App\Core\Command\Doctrine\EnsureProductionSettingsCommand: {tags: [console.command]}
    App\Core\Command\Doctrine\InfoCommand: {tags: [console.command]}
    App\Core\Command\Doctrine\MappingDescribeCommand: {tags: [console.command]}
    App\Core\Command\Doctrine\RunDqlCommand: {tags: [console.command]}
    App\Core\Command\Doctrine\RunSqlCommand: {tags: [console.command]}
    App\Core\Command\Doctrine\UpdateSchemaCommand: {tags: [console.command]}
    App\Core\Command\Doctrine\ValidateSchemaCommand: {tags: [console.command]}
    # End of - Commands.
