services:
    Doctrine\Migrations\Configuration\Migration\ExistingConfiguration:
        arguments: [!abstract configurations]

    Doctrine\Migrations\Configuration\EntityManager\ExistingEntityManager:
        arguments: ['@Doctrine\ORM\EntityManagerInterface']

    Doctrine\Migrations\DependencyFactory:
        factory: [Doctrine\Migrations\DependencyFactory, fromEntityManager]
        arguments:
            - '@Doctrine\Migrations\Configuration\Migration\ExistingConfiguration'
            - '@Doctrine\Migrations\Configuration\EntityManager\ExistingEntityManager'
            - '@Psr\Log\LoggerInterface'

    # Commands.
    Doctrine\Migrations\Tools\Console\Command\CurrentCommand:
        arguments: ['@Doctrine\Migrations\DependencyFactory', doctrine:migrations:current]
        tags: [{name: console.command, command: doctrine:migrations:current}]

    Doctrine\Migrations\Tools\Console\Command\DiffCommand:
        arguments: ['@Doctrine\Migrations\DependencyFactory', doctrine:migrations:diff]
        tags: [{name: console.command, command: doctrine:migrations:diff}]

    Doctrine\Migrations\Tools\Console\Command\DumpSchemaCommand:
        arguments: ['@Doctrine\Migrations\DependencyFactory', doctrine:migrations:dump-schema]
        tags: [{name: console.command, command: doctrine:migrations:dump-schema}]

    Doctrine\Migrations\Tools\Console\Command\ExecuteCommand:
        arguments: ['@Doctrine\Migrations\DependencyFactory', doctrine:migrations:execute]
        tags: [{name: console.command, command: doctrine:migrations:execute}]

    Doctrine\Migrations\Tools\Console\Command\GenerateCommand:
        arguments: ['@Doctrine\Migrations\DependencyFactory', doctrine:migrations:generate]
        tags: [{name: console.command, command: doctrine:migrations:generate}]

    Doctrine\Migrations\Tools\Console\Command\LatestCommand:
        arguments: ['@Doctrine\Migrations\DependencyFactory', doctrine:migrations:latest]
        tags: [{name: console.command, command: doctrine:migrations:latest}]

    Doctrine\Migrations\Tools\Console\Command\ListCommand:
        arguments: ['@Doctrine\Migrations\DependencyFactory', doctrine:migrations:list]
        tags: [{name: console.command, command: doctrine:migrations:list}]

    Doctrine\Migrations\Tools\Console\Command\MigrateCommand:
        arguments: ['@Doctrine\Migrations\DependencyFactory', doctrine:migrations:migrate]
        tags: [{name: console.command, command: doctrine:migrations:migrate}]

    Doctrine\Migrations\Tools\Console\Command\RollupCommand:
        arguments: ['@Doctrine\Migrations\DependencyFactory', doctrine:migrations:rollup]
        tags: [{name: console.command, command: doctrine:migrations:rollup}]

    Doctrine\Migrations\Tools\Console\Command\StatusCommand:
        arguments: ['@Doctrine\Migrations\DependencyFactory', doctrine:migrations:status]
        tags: [{name: console.command, command: doctrine:migrations:status}]

    Doctrine\Migrations\Tools\Console\Command\SyncMetadataCommand:
        arguments: ['@Doctrine\Migrations\DependencyFactory', doctrine:migrations:sync-metadata-storage]
        tags: [{name: console.command, command: doctrine:migrations:sync-metadata-storage}]

    Doctrine\Migrations\Tools\Console\Command\UpToDateCommand:
        arguments: ['@Doctrine\Migrations\DependencyFactory', doctrine:migrations:up-to-date]
        tags: [{name: console.command, command: doctrine:migrations:up-to-date}]

    Doctrine\Migrations\Tools\Console\Command\VersionCommand:
        arguments: ['@Doctrine\Migrations\DependencyFactory', doctrine:migrations:version]
        tags: [{name: console.command, command: doctrine:migrations:version}]
    # End of - Commands.
