services:
    kernel:
        class: App\Core\Kernel
        public: true
        synthetic: true

    Symfony\Component\EventDispatcher\EventDispatcher: ~
    Symfony\Component\EventDispatcher\EventDispatcherInterface: '@Symfony\Component\EventDispatcher\EventDispatcher'
    Psr\EventDispatcher\EventDispatcherInterface: '@Psr\EventDispatcher\EventDispatcherInterface'

    Symfony\Component\HttpKernel\Controller\ContainerControllerResolver:
        arguments: ['@service_container']

    Symfony\Component\HttpKernel\Controller\ControllerResolverInterface: '@Symfony\Component\HttpKernel\Controller\ContainerControllerResolver'

    Symfony\Component\HttpFoundation\RequestStack: ~

    Symfony\Component\HttpKernel\Controller\ArgumentResolver:
        arguments: [~, ~]

    Symfony\Component\HttpKernel\Controller\ArgumentResolverInterface: '@Symfony\Component\HttpKernel\Controller\ArgumentResolver'

    # Argument value resolvers.
    Symfony\Component\HttpKernel\Controller\ArgumentResolver\DefaultValueResolver:
        tags: [{name: controller.argument_value_resolver, priority: -32}]

    Symfony\Component\HttpKernel\Controller\ArgumentResolver\RequestAttributeValueResolver:
        tags: [{name: controller.argument_value_resolver, priority: 32}]

    Symfony\Component\HttpKernel\Controller\ArgumentResolver\RequestValueResolver:
        tags: [{name: controller.argument_value_resolver, priority: 16}]

    Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver:
        arguments: [~]
        tags: [{name: controller.argument_value_resolver, priority: -16}]

    Symfony\Component\HttpKernel\Controller\ArgumentResolver\SessionValueResolver:
        tags: [{name: controller.argument_value_resolver, priority: 16}]

    Symfony\Component\HttpKernel\Controller\ArgumentResolver\VariadicValueResolver:
        tags: [{name: controller.argument_value_resolver, priority: -64}]
    # End of - Argument value resolvers.

    Symfony\Component\HttpKernel\HttpKernel:
        arguments:
            - '@Symfony\Component\EventDispatcher\EventDispatcherInterface'
            - '@Symfony\Component\HttpKernel\Controller\ControllerResolverInterface'
            - '@Symfony\Component\HttpFoundation\RequestStack'
            - '@Symfony\Component\HttpKernel\Controller\ArgumentResolverInterface'

    Symfony\Component\HttpKernel\HttpKernelInterface:
        alias: Symfony\Component\HttpKernel\HttpKernel
        public: true
