parameters:
    property_access.magic_call: false
    property_access.throw_exception_on_invalid_index: false
    property_access.throw_exception_on_invalid_property_path: true

services:
    Symfony\Component\PropertyAccess\PropertyAccessor:
        arguments:
            - '%property_access.magic_call%'
            - '%property_access.throw_exception_on_invalid_index%'
            - '@cache.property_access'
            - '%property_access.throw_exception_on_invalid_property_path%'

    Symfony\Component\PropertyAccess\PropertyAccessorInterface: '@Symfony\Component\PropertyAccess\PropertyAccessor'
