services:
    # Extractors.
    Symfony\Component\PropertyInfo\Extractor\PhpDocExtractor:
        tags:
            - {name: property_info.type_extractor, priority: -1000}
            - {name: property_info.description_extractor, priority: -1000}

    Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor:
        tags:
            - {name: property_info.list_extractor, priority: -1002}
            - {name: property_info.type_extractor, priority: -1002}
            - {name: property_info.access_extractor, priority: -1000}
            - {name: property_info.initializable_extractor, priority: -1000}

    Symfony\Component\PropertyInfo\Extractor\SerializerExtractor:
        arguments: ['@Symfony\Component\Serializer\Mapping\Factory\ClassMetadataFactoryInterface']
        tags: [{name: property_info.list_extractor, priority: -1000}]
    # End of - Extractors.

    Symfony\Component\PropertyInfo\PropertyInfoExtractor:
        arguments:
            - !tagged_iterator property_info.list_extractor
            - !tagged_iterator property_info.type_extractor
            - !tagged_iterator property_info.description_extractor
            - !tagged_iterator property_info.access_extractor
            - !tagged_iterator property_info.initializable_extractor

    Symfony\Component\PropertyInfo\PropertyTypeExtractorInterface: '@Symfony\Component\PropertyInfo\PropertyInfoExtractor'
    Symfony\Component\PropertyInfo\PropertyDescriptionExtractorInterface: '@Symfony\Component\PropertyInfo\PropertyInfoExtractor'
    Symfony\Component\PropertyInfo\PropertyAccessExtractorInterface: '@Symfony\Component\PropertyInfo\PropertyInfoExtractor'
    Symfony\Component\PropertyInfo\PropertyListExtractorInterface: '@Symfony\Component\PropertyInfo\PropertyInfoExtractor'
    Symfony\Component\PropertyInfo\PropertyInfoExtractorInterface: '@Symfony\Component\PropertyInfo\PropertyInfoExtractor'
    Symfony\Component\PropertyInfo\PropertyInitializableExtractorInterface: '@Symfony\Component\PropertyInfo\PropertyInfoExtractor'

    Symfony\Component\PropertyInfo\PropertyInfoCacheExtractor:
        decorates: Symfony\Component\PropertyInfo\PropertyInfoExtractor
        arguments: ['@Symfony\Component\PropertyInfo\PropertyInfoCacheExtractor.inner', '@cache.property_info']
