services:
    App\Core\Routing\Loader:
        arguments: ['@Symfony\Component\Routing\Loader\PhpFileLoader', '%kernel.config_dir%', '%kernel.environment%']
        public: true

    routing.file_locator:
        class: Symfony\Component\Config\FileLocator

    routing.resolver:
        class: Symfony\Component\Config\Loader\LoaderResolver

    Symfony\Component\Routing\Loader\ContainerLoader:
        arguments: ['@service_container']
        tags: [routing.loader]

    Symfony\Component\Routing\Loader\GlobFileLoader:
        arguments: ['@routing.file_locator']
        tags: [routing.loader]

    Symfony\Component\Routing\Loader\PhpFileLoader:
        arguments: ['@routing.file_locator']
        tags: [routing.loader]

    Symfony\Component\Routing\Loader\YamlFileLoader:
        arguments: ['@routing.file_locator']
        tags: [routing.loader]

    routing.loader:
        class: Symfony\Component\Config\Loader\DelegatingLoader
        arguments: ['@routing.resolver']

    Symfony\Component\Routing\RequestContext: ~

    Symfony\Component\Routing\Router:
        arguments:
            - '@routing.loader'
            - App\Core\Routing\Loader::load
            -
                cache_dir: '%kernel.cache_dir%'
                debug: '%kernel.debug%'
                resource_type: service
            - '@Symfony\Component\Routing\RequestContext'

    Symfony\Component\Routing\RouterInterface: '@Symfony\Component\Routing\Router'
    Symfony\Component\Routing\Generator\UrlGeneratorInterface: '@Symfony\Component\Routing\Router'
    Symfony\Component\Routing\Matcher\RequestMatcherInterface: '@Symfony\Component\Routing\Router'
    Symfony\Component\Routing\Matcher\UrlMatcherInterface: '@Symfony\Component\Routing\Router'

    Symfony\Component\HttpKernel\EventListener\RouterListener:
        arguments:
            - '@Symfony\Component\Routing\Matcher\RequestMatcherInterface'
            - '@Symfony\Component\HttpFoundation\RequestStack'
            - '@Symfony\Component\Routing\RequestContext'
            - '@Psr\Log\LoggerInterface'
            - '%kernel.project_dir%'
            - '%kernel.debug%'
        tags: [kernel.event_subscriber]
