services:
    # Encoders.
    Symfony\Component\Security\Core\Encoder\EncoderFactory:
        arguments: [!abstract encoders]

    Symfony\Component\Security\Core\Encoder\EncoderFactoryInterface: '@Symfony\Component\Security\Core\Encoder\EncoderFactory'

    Symfony\Component\Security\Core\Encoder\UserPasswordEncoder:
        arguments: ['@Symfony\Component\Security\Core\Encoder\EncoderFactoryInterface']

    Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface: '@Symfony\Component\Security\Core\Encoder\UserPasswordEncoder'
    # End of - Encoders.

    # Authentication.
    Symfony\Component\Security\Core\Authentication\AuthenticationTrustResolver: ~
    Symfony\Component\Security\Core\Authentication\AuthenticationTrustResolverInterface: '@Symfony\Component\Security\Core\Authentication\AuthenticationTrustResolver'

    Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage: ~
    Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface: '@Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage'

    Symfony\Component\Security\Core\User\UserChecker: ~
    Symfony\Component\Security\Core\User\UserCheckerInterface: '@Symfony\Component\Security\Core\User\UserChecker'

    Symfony\Component\Security\Http\Authentication\AuthenticatorManager:
        abstract: true
        arguments:
            - !abstract authenticators
            - '@Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface'
            - !abstract event dispatcher
            - !abstract firewall
            - '@Psr\Log\LoggerInterface'
            - !abstract erase credentials

    Symfony\Component\Security\Http\Authentication\NoopAuthenticationManager: ~
    Symfony\Component\Security\Core\Authentication\AuthenticationManagerInterface: '@Symfony\Component\Security\Http\Authentication\NoopAuthenticationManager'

    Symfony\Component\Security\Http\EntryPoint\RetryAuthenticationEntryPoint:
        arguments: [!abstract HTTP port, !abstract HTTPS port]

    Symfony\Component\Security\Http\Firewall:
        arguments:
            - '@Symfony\Component\Security\Http\FirewallMap'
            - '@Symfony\Contracts\EventDispatcher\EventDispatcherInterface'
        tags: [kernel.event_subscriber]

    Symfony\Component\Security\Http\FirewallMap: ~
    Symfony\Component\Security\Http\FirewallMapInterface: '@Symfony\Component\Security\Http\FirewallMap'

    Symfony\Component\Security\Http\Logout\LogoutUrlGenerator:
        arguments:
            - '@Symfony\Component\HttpFoundation\RequestStack'
            - '@Symfony\Component\Routing\Generator\UrlGeneratorInterface'
            - '@Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface'

    Symfony\Component\Security\Http\Session\SessionAuthenticationStrategy:
        arguments: [!abstract strategy]

    Symfony\Component\Security\Http\Session\SessionAuthenticationStrategyInterface: '@Symfony\Component\Security\Http\Session\SessionAuthenticationStrategy'

    # Listeners.
    Symfony\Component\Security\Http\EventListener\CheckCredentialsListener:
        arguments: ['@Symfony\Component\Security\Core\Encoder\EncoderFactoryInterface']
        tags: [kernel.event_subscriber]

    Symfony\Component\Security\Http\EventListener\CookieClearingLogoutListener:
        abstract: true
        arguments: [!abstract cookies]

    Symfony\Component\Security\Http\EventListener\CsrfProtectionListener:
        arguments: ['@Symfony\Component\Security\Csrf\CsrfTokenManagerInterface']
        tags: [kernel.event_subscriber]

    Symfony\Component\Security\Http\EventListener\CsrfTokenClearingLogoutListener:
        arguments: ['@Symfony\Component\Security\Csrf\TokenStorage\ClearableTokenStorageInterface']
        tags: [kernel.event_subscriber]

    Symfony\Component\Security\Http\EventListener\DefaultLogoutListener:
        abstract: true
        arguments: ['@Symfony\Component\Security\Http\HttpUtils', !abstract target URL]

    Symfony\Component\Security\Http\EventListener\PasswordMigratingListener:
        arguments: ['@Symfony\Component\Security\Core\Encoder\EncoderFactoryInterface']
        tags: [kernel.event_subscriber]

    Symfony\Component\Security\Http\EventListener\SessionLogoutListener: ~

    Symfony\Component\Security\Http\EventListener\SessionStrategyListener:
        arguments: ['@Symfony\Component\Security\Http\Session\SessionAuthenticationStrategyInterface']

    Symfony\Component\Security\Http\EventListener\UserCheckerListener:
        abstract: true
        arguments: [!abstract user checker]
    # End of - Listeners.

    # Firewalls.
    Symfony\Component\Security\Http\Firewall\AccessListener:
        arguments:
            - '@Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface'
            - '@Symfony\Component\Security\Core\Authorization\AccessDecisionManagerInterface'
            - '@Symfony\Component\Security\Http\AccessMapInterface'
            - '@Symfony\Component\Security\Core\Authentication\AuthenticationManagerInterface'
            - false

    Symfony\Component\Security\Http\Firewall\AnonymousAuthenticationListener:
        arguments:
            - '@Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface'
            - !abstract secret
            - '@Psr\Log\LoggerInterface'
            - '@Symfony\Component\Security\Core\Authentication\AuthenticationManagerInterface'

    Symfony\Component\Security\Http\Firewall\AuthenticatorManagerListener:
        abstract: true
        arguments: [!abstract authenticator manager]

    Symfony\Component\Security\Http\Firewall\ChannelListener:
        arguments:
            - '@Symfony\Component\Security\Http\AccessMapInterface'
            - '@Symfony\Component\Security\Http\EntryPoint\RetryAuthenticationEntryPoint'
            - '@Psr\Log\LoggerInterface'

    Symfony\Component\Security\Http\Firewall\ContextListener:
        abstract: true
        arguments:
            - '@Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface'
            - !abstract user providers
            - !abstract firewall
            - '@Psr\Log\LoggerInterface'
            - '@Symfony\Contracts\EventDispatcher\EventDispatcherInterface'
            - '@Symfony\Component\Security\Core\Authentication\AuthenticationTrustResolverInterface'

    Symfony\Component\Security\Http\Firewall\ExceptionListener:
        abstract: true
        arguments:
            - '@Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface'
            - '@Symfony\Component\Security\Core\Authentication\AuthenticationTrustResolverInterface'
            - '@Symfony\Component\Security\Http\HttpUtils'
            - !abstract firewall
            - !abstract authentication entry point
            - !abstract error page
            - !abstract access denied handler
            - '@Psr\Log\LoggerInterface'
            - !abstract stateless

    Symfony\Component\Security\Http\Firewall\LogoutListener:
        abstract: true
        arguments:
            - '@Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface'
            - '@Symfony\Component\Security\Http\HttpUtils'
            - !abstract event dispatcher
            - !abstract options
            - !abstract csrf token manager
    # End of - Firewalls.
    # End of - Authentication.

    # Authorization.
    Symfony\Component\Security\Core\Authorization\AccessDecisionManager:
        arguments:
            - !tagged_iterator security.voter
            - !abstract strategy
            - !abstract allow if all abstain decisions
            - !abstract allow if equal granted denied decisions

    Symfony\Component\Security\Core\Authorization\AccessDecisionManagerInterface: '@Symfony\Component\Security\Core\Authorization\AccessDecisionManager'

    Symfony\Component\Security\Core\Authorization\AuthorizationChecker:
        arguments:
            - '@Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface'
            - '@Symfony\Component\Security\Core\Authentication\AuthenticationManagerInterface'
            - '@Symfony\Component\Security\Core\Authorization\AccessDecisionManagerInterface'
            - false
            - false

    Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface: '@Symfony\Component\Security\Core\Authorization\AuthorizationChecker'

    Symfony\Component\Security\Http\AccessMap: ~
    Symfony\Component\Security\Http\AccessMapInterface: '@Symfony\Component\Security\Http\AccessMap'

    # Voters.
    Symfony\Component\Security\Core\Authorization\Voter\AuthenticatedVoter:
        arguments: ['@Symfony\Component\Security\Core\Authentication\AuthenticationTrustResolverInterface']
        tags: [security.voter]

    Symfony\Component\Security\Core\Authorization\Voter\RoleVoter:
        tags: [security.voter]
    # End of - Voters.
    # End of - Authorization.

    # CSRF.
    Symfony\Component\Security\Csrf\TokenGenerator\UriSafeTokenGenerator: ~
    Symfony\Component\Security\Csrf\TokenGenerator\TokenGeneratorInterface: '@Symfony\Component\Security\Csrf\TokenGenerator\UriSafeTokenGenerator'

    Symfony\Component\Security\Csrf\TokenStorage\SessionTokenStorage:
        arguments: ['@Symfony\Component\HttpFoundation\Session\SessionInterface']

    Symfony\Component\Security\Csrf\TokenStorage\TokenStorageInterface: '@Symfony\Component\Security\Csrf\TokenStorage\SessionTokenStorage'
    Symfony\Component\Security\Csrf\TokenStorage\ClearableTokenStorageInterface: '@Symfony\Component\Security\Csrf\TokenStorage\SessionTokenStorage'

    Symfony\Component\Security\Csrf\CsrfTokenManager:
        arguments:
            - '@Symfony\Component\Security\Csrf\TokenGenerator\TokenGeneratorInterface'
            - '@Symfony\Component\Security\Csrf\TokenStorage\TokenStorageInterface'
            - '@Symfony\Component\HttpFoundation\RequestStack'

    Symfony\Component\Security\Csrf\CsrfTokenManagerInterface: '@Symfony\Component\Security\Csrf\CsrfTokenManager'
    # End of - CSRF.

    # Other.
    Symfony\Component\Security\Http\HttpUtils:
        arguments:
            - '@Symfony\Component\Routing\Generator\UrlGeneratorInterface'
            - '@Symfony\Component\Routing\Matcher\UrlMatcherInterface'
    # End of - Other.
