services:
    # Encoders.
    Symfony\Component\Security\Core\Encoder\EncoderFactory: ~
    Symfony\Component\Security\Core\Encoder\EncoderFactoryInterface: '@Symfony\Component\Security\Core\Encoder\EncoderFactory'

    Symfony\Component\Security\Core\Encoder\UserPasswordEncoder:
        arguments: ['@Symfony\Component\Security\Core\Encoder\EncoderFactoryInterface']

    Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface: '@Symfony\Component\Security\Core\Encoder\UserPasswordEncoder'
    # End of - Encoders.
