services:
    App\Core\Templating\Helper\AssetsHelper:
        arguments: ['@Symfony\Component\Asset\PackageInterface']
        tags: [templating.helper]

    Symfony\Component\Templating\Helper\SlotsHelper:
        tags: [templating.helper]

    App\Core\Templating\EngineFactory:
        arguments: ['%kernel.project_dir%', !tagged_iterator templating.helper]

    Symfony\Component\Templating\EngineInterface:
        factory: ['@App\Core\Templating\EngineFactory', factory]
