parameters:
    validator.mapping.cache.file: '%kernel.cache_dir%/validation.php'

services:
    Symfony\Component\Validator\ContainerConstraintValidatorFactory:
        arguments: [!abstract constraint validators container]

    validator.mapping.cache:
        class: Psr\Cache\CacheItemPoolInterface
        factory: [Symfony\Component\Cache\Adapter\PhpArrayAdapter, create]
        arguments: ['%validator.mapping.cache.file%', '@cache.validator']

    Symfony\Component\Validator\ValidatorBuilder:
        factory: [Symfony\Component\Validator\Validation, createValidatorBuilder]
        calls: [[setConstraintValidatorFactory, ['@Symfony\Component\Validator\ContainerConstraintValidatorFactory']]]

    Symfony\Component\Validator\Validator\ValidatorInterface:
        factory: ['@Symfony\Component\Validator\ValidatorBuilder', getValidator]

    # Constraint validators.
    Symfony\Component\Validator\Constraints\EmailValidator:
        arguments: [!abstract default mode]
        tags: [validator.constraint_validator]
    # End of - Constraint validators.
